spring:
  profiles:
    include: data
  output:
    ansi:
      enabled: always # 로그 색상 추가
  datasource:
    url: jdbc:mysql://localhost:3306/uniqon?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: uniqon
    driver-class-name: com.mysql.cj.jdbc.Driver # MySql 드라이버 설정
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  redis:
    host: redis
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  blacklist:
    access-token: BlackList_AccessToken_


