spring:
  profiles:
    include: API-KEY
  output:
    ansi:
      enabled: always # 로그 색상 추가
  datasource:
    url: jdbc:mysql://localhost:3306/uniqon?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: uniqon
    driver-class-name: com.mysql.cj.jdbc.Driver # MySql 드라이버 설정
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  redis:
    host: redis
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

ethereum:
  server:
    ip: localhost
    port: 7545
  contract:
    address: "0xE765ac275D87F4201b0a453617Ed6717aEe5e540"


logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  blacklist:
    access-token: BlackList_AccessToken_


