spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uniqon?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: uniqon
    password: brc9g5U4PQwC4du